name: GitHub Classroom Workflow

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  Checking-Solution:
    runs-on: gtest
    timeout-minutes: 3
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Check repository clean
        run: ./scripts/check_clean.sh
      - name: Check requirements
        run: |
             !(grep -qwRE --include=*.{cc,cpp,h,hpp} '<vector>|<list>|<string>|<algorithm>|<stack>|<queue>|<deque>|<set>|<map>|<bits' ./* ) &&  (echo \"Check - OK\" )  || ( echo \"Forbiden STL containers\" && exit 9 )
      - name: Check code style
        run: |
             clang-format --version
             find "." \( -name '*.cpp' -o -name '*.h*' \) -print0 | xargs -0 clang-format --dry-run --Werror --verbose
      - name: Code linting
        uses: amcp-pit/cpp-linter@v1
        with:
          extra-args-before: '-xc++'
          extra-args: '-std=c++20'
          after-args: '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON'
      - name: Build
        run: ./scripts/build.sh
      - name: Test 1
        id: test-1
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Test 1 (n=1)
          setup-command: ''
          command: "timeout 1 ./build/numofsolutions"
          input: "1 1000"
          expected-output: "1"
          comparison-method: exact
          timeout: 1
          max-score: 1
      - name: Test 2
        id: test-2
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Test 2 (n=4)
          setup-command: ''
          command: "timeout 1 ./build/numofsolutions"
          input: "4 1000"
          expected-output: "5"
          comparison-method: exact
          timeout: 1
          max-score: 1
      - name: Test 3
        id: test-3
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Test 3 (n=10)
          setup-command: ''
          command: "timeout 1 ./build/numofsolutions"
          input: "10 1000"
          expected-output: "42"
          comparison-method: exact
          timeout: 1
          max-score: 1
      - name: Test 4
        id: test-4
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Test 4 (n=20)
          setup-command: ''
          command: "ulimit -Sv 8000 && timeout 1 ./build/numofsolutions || ( rc=$?;  if [ ${rc} -eq 124 ]; then echo \"Timeout\"; fi ; exit ${rc} ) "
          input: "20 1000"
          expected-output: "627"
          comparison-method: exact
          timeout: 1
          max-score: 1
      - name: Test 5
        id: test-5
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Test 5 (n=49)
          setup-command: ''
          command: "ulimit -Sv 8000 && timeout 1 ./build/numofsolutions || ( rc=$?;  if [ ${rc} -eq 124 ]; then echo \"Timeout\"; fi ; exit ${rc} ) "
          input: "49 1000000"
          expected-output: "173525"
          comparison-method: exact
          timeout: 1
          max-score: 1
      - name: Test 6
        id: test-6
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Test 6 (n=100)
          setup-command: ''
          command: "ulimit -Sv 8000 && timeout 1 ./build/numofsolutions || ( rc=$?;  if [ ${rc} -eq 124 ]; then echo \"Timeout\"; fi ; exit ${rc} ) "
          input: "100 1000000000000"
          expected-output: "190569292"
          comparison-method: exact
          timeout: 1
          max-score: 1
      - name: Test 7
        id: test-7
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Test 7 (n=999)
          setup-command: ''
          command: "ulimit -Sv 8000 && timeout 1 ./build/numofsolutions || ( rc=$?;  if [ ${rc} -eq 124 ]; then echo \"Timeout\"; fi ; exit ${rc} ) "
          input: "999 1000000000000"
          expected-output: "880444632250"
          comparison-method: exact
          timeout: 1
          max-score: 1
      - name: Test 8
        id: test-8
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Test 8 (n=1000)
          setup-command: ''
          command: "ulimit -Sv 8000 && timeout 1 ./build/numofsolutions || ( rc=$?;  if [ ${rc} -eq 124 ]; then echo \"Timeout\"; fi ; exit ${rc} ) "
          input: "1000 1000000000000"
          expected-output: "692149727991"
          comparison-method: exact
          timeout: 1
          max-score: 1
      - name: Test 9
        id: test-9
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Test 9 (n=1001)
          setup-command: ''
          command: "ulimit -Sv 8000 && timeout 1 ./build/numofsolutions || ( rc=$?;  if [ ${rc} -eq 124 ]; then echo \"Timeout\"; fi ; exit ${rc} ) "
          input: "1001 1000000000000"
          expected-output: "13218349796"
          comparison-method: exact
          timeout: 1
          max-score: 1
      - name: Test 10
        id: test-10
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Test 10 (n=10000)
          setup-command: ''
          command: "ulimit -Sv 8000 && timeout 3 ./build/numofsolutions || ( rc=$?;  if [ ${rc} -eq 124 ]; then echo \"Timeout\"; fi ; exit ${rc} ) "
          input: "10000 1000000000000"
          expected-output: "906916435144"
          comparison-method: exact
          timeout: 1
          max-score: 1
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TEST-1_RESULTS: "${{steps.test-1.outputs.result}}"
          TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
          TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
          TEST-4_RESULTS: "${{steps.test-4.outputs.result}}"
          TEST-5_RESULTS: "${{steps.test-5.outputs.result}}"
          TEST-6_RESULTS: "${{steps.test-6.outputs.result}}"
          TEST-7_RESULTS: "${{steps.test-7.outputs.result}}"
          TEST-8_RESULTS: "${{steps.test-8.outputs.result}}"
          TEST-9_RESULTS: "${{steps.test-9.outputs.result}}"
          TEST-10_RESULTS: "${{steps.test-10.outputs.result}}"
        with:
          runners: test-1,test-2,test-3,test-4,test-5,test-6,test-7,test-8,test-9,test-10
      - name: Memory leaks
        run: |
             echo "1000 1000000" | valgrind --tool=memcheck --leak-check=full --undef-value-errors=no --error-exitcode=111 ./build/numofsolutions
      - name: Checkout
        uses: actions/checkout@v4
      - name: CPD
        uses: amcp-pit/cpd-action@v1
        id: cpd
        with:
          repository: ${{ github.repository }}
          collection: ${{ github.repository_owner  }}
      - name: Clean
        run: |
             rm -rf ./* || true
             rm -rf ./.??* || true
